"""add cascades, FKs, indexes, CHECK constraints

Revision ID: 7e455c8b2c74
Revises: 3715cfc8a646
Create Date: 2026-02-11 22:12:55.503212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e455c8b2c74'
down_revision: Union[str, Sequence[str], None] = '3715cfc8a646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: CHECK constraints defined in models via __table_args__ - will be added in a future migration
    # Auto-generated CASCADE and index changes
    # Note: Removed partition table operations - they're unrelated to this migration
    op.drop_constraint(op.f('call_logs_conversation_id_fkey'), 'call_logs', type_='foreignkey')
    op.create_foreign_key('call_logs_conversation_id_fkey', 'call_logs', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('channel_configs_workspace_id_fkey'), 'channel_configs', type_='foreignkey')
    op.create_foreign_key('channel_configs_workspace_id_fkey', 'channel_configs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('conversations_workspace_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_workspace_id_fkey', 'conversations', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('documents_kb_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key('documents_kb_id_fkey', 'documents', 'knowledge_bases', ['kb_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('escalation_rules_workspace_id_fkey'), 'escalation_rules', type_='foreignkey')
    op.create_foreign_key('escalation_rules_workspace_id_fkey', 'escalation_rules', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('knowledge_bases_workspace_id_fkey'), 'knowledge_bases', type_='foreignkey')
    op.create_foreign_key('knowledge_bases_workspace_id_fkey', 'knowledge_bases', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('knowledge_gaps_workspace_id_fkey'), 'knowledge_gaps', type_='foreignkey')
    op.create_foreign_key('knowledge_gaps_workspace_id_fkey', 'knowledge_gaps', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # Create composite index for efficient message listing (use raw SQL for IF NOT EXISTS)
    op.execute("CREATE INDEX IF NOT EXISTS idx_messages_conversation_time ON messages (conversation_id, created_at DESC)")
    # Note: messages FK not created - partitioned tables require per-partition FKs in PostgreSQL
    op.drop_constraint(op.f('webhook_actions_workspace_id_fkey'), 'webhook_actions', type_='foreignkey')
    op.create_foreign_key('webhook_actions_workspace_id_fkey', 'webhook_actions', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('webhook_outbox_workspace_id_fkey'), 'webhook_outbox', type_='foreignkey')
    op.create_foreign_key('webhook_outbox_workspace_id_fkey', 'webhook_outbox', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Auto-generated downgrade
    op.drop_constraint('webhook_outbox_workspace_id_fkey', 'webhook_outbox', type_='foreignkey')
    op.create_foreign_key(op.f('webhook_outbox_workspace_id_fkey'), 'webhook_outbox', 'workspaces', ['workspace_id'], ['id'])
    op.drop_constraint('webhook_actions_workspace_id_fkey', 'webhook_actions', type_='foreignkey')
    op.create_foreign_key(op.f('webhook_actions_workspace_id_fkey'), 'webhook_actions', 'workspaces', ['workspace_id'], ['id'])
    # Note: messages FK doesn't exist (partitioned table limitation)
    op.drop_index('idx_messages_conversation_time', table_name='messages')
    op.drop_constraint('knowledge_gaps_workspace_id_fkey', 'knowledge_gaps', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_gaps_workspace_id_fkey'), 'knowledge_gaps', 'workspaces', ['workspace_id'], ['id'])
    op.drop_constraint('knowledge_bases_workspace_id_fkey', 'knowledge_bases', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_bases_workspace_id_fkey'), 'knowledge_bases', 'workspaces', ['workspace_id'], ['id'])
    op.drop_constraint('escalation_rules_workspace_id_fkey', 'escalation_rules', type_='foreignkey')
    op.create_foreign_key(op.f('escalation_rules_workspace_id_fkey'), 'escalation_rules', 'workspaces', ['workspace_id'], ['id'])
    op.drop_constraint('documents_kb_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_kb_id_fkey'), 'documents', 'knowledge_bases', ['kb_id'], ['id'])
    op.drop_constraint('conversations_workspace_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_workspace_id_fkey'), 'conversations', 'workspaces', ['workspace_id'], ['id'])
    op.drop_constraint('channel_configs_workspace_id_fkey', 'channel_configs', type_='foreignkey')
    op.create_foreign_key(op.f('channel_configs_workspace_id_fkey'), 'channel_configs', 'workspaces', ['workspace_id'], ['id'])
    op.drop_constraint('call_logs_conversation_id_fkey', 'call_logs', type_='foreignkey')
    op.create_foreign_key(op.f('call_logs_conversation_id_fkey'), 'call_logs', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###
